export const APP_TYPES = {
    APP: Symbol('APP'),
    DATABASE_SERVICE: Symbol('DATABASE_SERVICE'),
    CONFIG_SERVICE: Symbol('CONFIG_SERVICE'),
    LOGGER_SERVICE: Symbol('LOGGER_SERVICE'),
    EXCEPTION_FILTER: Symbol('EXCEPTION_FILTER'),

    AUTH_CONTROLLER: Symbol('AUTH_CONTROLLER'),
    AUTH_SERVICE: Symbol('AUTH_SERVICE'),

    USER_REPOSITORY: Symbol('USER_REPOSITORY'),

};
