export const APP_TYPES = {
    APP: Symbol('APP'),

    DATABASE_SERVICE: Symbol('DATABASE_SERVICE'),
    CONFIG_SERVICE: Symbol('CONFIG_SERVICE'),
    LOGGER_SERVICE: Symbol('LOGGER_SERVICE'),
    EXCEPTION_FILTER: Symbol('EXCEPTION_FILTER'),
    JWT_SERVICE: Symbol('JWT_SERVICE'),
    AUTH_GUARD_FACTORY: Symbol('AUTH_GUARD_FACTORY'),
    AUTH_MIDDLEWARE: Symbol('AUTH_MIDDLEWARE'),

    EMAIL_SERVICE: Symbol('EMAIL_SERVICE'),
    S3_SERVICE: Symbol('S3_SERVICE'),

    UPLOAD_CONTROLLER: Symbol('UPLOAD_CONTROLLER'),

    AUTH_CONTROLLER: Symbol('AUTH_CONTROLLER'),
    AUTH_SERVICE: Symbol('AUTH_SERVICE'),

    REFRESH_TOKEN_REPOSITORY: Symbol('REFRESH_TOKEN_REPOSITORY'),

    USER_CONTROLLER: Symbol('USER_SERVICE'),
    USER_SERVICE: Symbol('USER_SERVICE'),
    USER_REPOSITORY: Symbol('USER_REPOSITORY'),

    PRODUCT_CONTROLLER: Symbol('PRODUCT_CONTROLLER'),
    PRODUCT_SERVICE: Symbol('PRODUCT_SERVICE'),
    PRODUCT_REPOSITORY: Symbol('PRODUCT_REPOSITORY'),

    CART_CONTROLLER: Symbol('CART_CONTROLLER'),
    CART_SERVICE: Symbol('CART_SERVICE'),
    CART_REPOSITORY: Symbol('CART_REPOSITORY'),

    ADDRESS_CONTROLLER: Symbol('ADDRESS_CONTROLLER'),
    ADDRESS_SERVICE: Symbol('ADDRESS_SERVICE'),
    ADDRESS_REPOSITORY: Symbol('ADDRESS_REPOSITORY'),

    ORDER_CONTROLLER: Symbol('ORDER_CONTROLLER'),
    ORDER_SERVICE: Symbol('ORDER_SERVICE'),
    ORDER_REPOSITORY: Symbol('ORDER_REPOSITORY'),

    PAYMENT_METHOD_REPOSITORY: Symbol('PAYMENT_METHOD_REPOSITORY'),
    PAYMENT_METHOD_CONTROLLER: Symbol('PAYMENT_METHOD_CONTROLLER'),
    PAYMENT_METHOD_SERVICE: Symbol('PAYMENT_METHOD_SERVICE'),

    YOOKASSA_SERVICE: Symbol('YOOKASSA_SERVICE'),
    YOOKASSA_CONTROLLER: Symbol('YOOKASSA_CONTROLLER'),

    FAVORITES_CONTROLLER: Symbol('FAVORITES_CONTROLLER'),
    FAVORITES_SERVICE: Symbol('FAVORITES_SERVICE'),
    FAVORITES_REPOSITORY: Symbol('FAVORITES_REPOSITORY'),

    REVIEW_CONTROLLER: Symbol('REVIEW_CONTROLLER'),
    REVIEW_SERVICE: Symbol('REVIEW_SERVICE'),
    REVIEW_REPOSITORY: Symbol('REVIEW_REPOSITORY'),

    LIKE_CONTROLLER: Symbol('LIKE_CONTROLLER'),
    LIKE_SERVICE: Symbol('LIKE_SERVICE'),
    LIKE_REPOSITORY: Symbol('LIKE_REPOSITORY'),
};
