export const APP_TYPES = {
    APP: Symbol('APP'),
    DATABASE_SERVICE: Symbol('DATABASE_SERVICE'),
    CONFIG_SERVICE: Symbol('CONFIG_SERVICE'),
    LOGGER_SERVICE: Symbol('LOGGER_SERVICE'),
    EXCEPTION_FILTER: Symbol('EXCEPTION_FILTER'),
    JWT_SERVICE: Symbol('JWT_SERVICE'),
    EMAIL_SERVICE: Symbol('EMAIL_SERVICE'),
    AUTH_GUARD_FACTORY: Symbol('AUTH_GUARD_FACTORY'),

    AUTH_CONTROLLER: Symbol('AUTH_CONTROLLER'),
    AUTH_SERVICE: Symbol('AUTH_SERVICE'),

    REFRESH_TOKEN_REPOSITORY: Symbol('REFRESH_TOKEN_REPOSITORY'),

    USER_REPOSITORY: Symbol('USER_REPOSITORY'),

    PRODUCT_CONTROLLER: Symbol('PRODUCT_CONTROLLER'),
    PRODUCT_SERVICE: Symbol('PRODUCT_SERVICE'),
    PRODUCT_REPOSITORY: Symbol('PRODUCT_REPOSITORY'),
};
